In [ ]:
# MID Term Exam 10/09/2026
# ==============================
# STEP 1 : Import Required Libraries
# ==============================

# Used for handling datasets
import pandas as pd

# Used for numerical operations
import numpy as np

# Used for splitting data into training and testing
from sklearn.model_selection import train_test_split

# Used for feature scaling
from sklearn.preprocessing import StandardScaler

# TensorFlow is the main deep learning library
import tensorflow as tf

# Keras is used to build the Artificial Neural Network
from tensorflow.keras.models import Sequential

# Dense is used to create ANN layers
from tensorflow.keras.layers import Dense

# Used to evaluate model performance
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [2]:
# Load the dataset
df = pd.read_csv("House Price India.csv")

# Display first 5 rows
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [3]:
# Check dataset information
df.info()

# Check dataset shape
print(df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14619 non-null  int64
 1   Date                                   14619 non-null  int64
 2   number of bedrooms                     14619 non-null  int64
 3   number of bathrooms                    14619 non-null  float64
 4   living area                            14619 non-null  int64
 5   lot area                               14619 non-null  int64
 6   number of floors                       14619 non-null  float64
 7   waterfront present                     14619 non-null  int64
 8   number of views                        14619 non-null  int64
 9   condition of the house                 14619 non-null  int64
 10  grade of the house                     14619 non-null  int64
 11  Area of the house(excluding basement)  14619 non-null  int64
 12  Area of the basement                   14619 non-null  int64
 13  Built Year                             14619 non-null  int64
 14  Renovation Year                        14619 non-null  int64
 15  Postal Code                            14619 non-null  int64
 16  Lattitude                              14619 non-null  float64
 17  Longitude                              14619 non-null  float64
 18  living_area_renov                      14619 non-null  int64
 19  lot_area_renov                         14619 non-null  int64
 20  Number of schools nearby               14619 non-null  int64
 21  Distance from the airport              14619 non-null  int64
 22  Price                                  14619 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB
(14619, 23)

In [4]:
# Input features
X = df.drop("Price", axis=1)

# Target variable
y = df["Price"]

In [5]:
# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [6]:
# Feature Scaling

# Create scaler object
scaler = StandardScaler()

# Scale training data
X_train = scaler.fit_transform(X_train)

# Scale testing data
X_test = scaler.transform(X_test)

In [7]:

# Create the ANN model
model = Sequential()

# Input layer + First Hidden Layer
model.add(Dense(units=64, activation='relu', input_shape=(X_train.shape[1],)))

# Second Hidden Layer
model.add(Dense(units=32, activation='relu'))

# Output Layer (1 neuron for regression)
model.add(Dense(units=1, activation='linear'))

c:\Users\Lenovo\OneDrive\Desktop\Advance DSL\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [8]:
# Compile the ANN model
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [9]:
# Train the ANN model
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 423995932672.0000 - mae: 539001.5625 - val_loss: 410111410176.0000 - val_mae: 535648.6875
Epoch 2/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 419707060224.0000 - mae: 536455.4375 - val_loss: 401606148096.0000 - val_mae: 530403.7500
Epoch 3/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 405169340416.0000 - mae: 527639.0000 - val_loss: 380846014464.0000 - val_mae: 517372.2188
Epoch 4/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 377398525952.0000 - mae: 510128.5312 - val_loss: 346434306048.0000 - val_mae: 494763.5625
Epoch 5/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 335712976896.0000 - mae: 482438.9375 - val_loss: 299501518848.0000 - val_mae: 461431.9688
Epoch 6/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 284801728512.0000 - mae: 444557.2812 - val_loss: 246773383168.0000 - val_mae: 419180.4688
Epoch 7/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 230710067200.0000 - mae: 399231.5625 - val_loss: 194145910784.0000 - val_mae: 369847.7500
Epoch 8/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 180496728064.0000 - mae: 348843.9375 - val_loss: 149723136000.0000 - val_mae: 319557.3750
Epoch 9/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 139583422464.0000 - mae: 300773.4375 - val_loss: 115501359104.0000 - val_mae: 274434.6875
Epoch 10/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 110159429632.0000 - mae: 262460.1875 - val_loss: 92966969344.0000 - val_mae: 242948.4531
Epoch 11/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91569897472.0000 - mae: 237070.1719 - val_loss: 79540297728.0000 - val_mae: 222205.2656
Epoch 12/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 80387039232.0000 - mae: 219618.4375 - val_loss: 71201718272.0000 - val_mae: 207460.0000
Epoch 13/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 73286492160.0000 - mae: 207085.0781 - val_loss: 65542950912.0000 - val_mae: 196623.5000
Epoch 14/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 68329984000.0000 - mae: 197537.1094 - val_loss: 61422178304.0000 - val_mae: 188596.6094
Epoch 15/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 64703279104.0000 - mae: 190286.1250 - val_loss: 58239152128.0000 - val_mae: 182443.4688
Epoch 16/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 61912948736.0000 - mae: 184759.0625 - val_loss: 55767498752.0000 - val_mae: 177613.5938
Epoch 17/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59710242816.0000 - mae: 180448.6562 - val_loss: 53746024448.0000 - val_mae: 173777.7656
Epoch 18/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 57940099072.0000 - mae: 177030.9219 - val_loss: 52006518784.0000 - val_mae: 170496.2969
Epoch 19/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56389382144.0000 - mae: 173883.2188 - val_loss: 50471870464.0000 - val_mae: 167606.2812
Epoch 20/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54979055616.0000 - mae: 170897.2188 - val_loss: 49050148864.0000 - val_mae: 164911.4375
Epoch 21/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53639524352.0000 - mae: 168343.5781 - val_loss: 47636815872.0000 - val_mae: 162191.4219
Epoch 22/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52362108928.0000 - mae: 165427.4531 - val_loss: 46316208128.0000 - val_mae: 159642.8906
Epoch 23/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51137875968.0000 - mae: 162863.3281 - val_loss: 45004009472.0000 - val_mae: 157002.9219
Epoch 24/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49907822592.0000 - mae: 160049.8438 - val_loss: 43757400064.0000 - val_mae: 154451.0312
Epoch 25/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48703328256.0000 - mae: 157257.3125 - val_loss: 42501746688.0000 - val_mae: 151783.1719
Epoch 26/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47543848960.0000 - mae: 154568.0625 - val_loss: 41289637888.0000 - val_mae: 149212.8281
Epoch 27/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46380429312.0000 - mae: 151750.0000 - val_loss: 40087937024.0000 - val_mae: 146557.4844
Epoch 28/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45230505984.0000 - mae: 148761.0156 - val_loss: 38941818880.0000 - val_mae: 144049.5781
Epoch 29/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 44133376000.0000 - mae: 146133.6250 - val_loss: 37806166016.0000 - val_mae: 141460.0938
Epoch 30/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 43031724032.0000 - mae: 143372.6562 - val_loss: 36703170560.0000 - val_mae: 138836.3750
Epoch 31/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 41971073024.0000 - mae: 140232.0938 - val_loss: 35614179328.0000 - val_mae: 136177.0938
Epoch 32/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40919486464.0000 - mae: 137683.0781 - val_loss: 34559639552.0000 - val_mae: 133494.3750
Epoch 33/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39899889664.0000 - mae: 135064.2656 - val_loss: 33507710976.0000 - val_mae: 130511.5391
Epoch 34/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38922121216.0000 - mae: 131554.5000 - val_loss: 32509829120.0000 - val_mae: 127887.8281
Epoch 35/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37943472128.0000 - mae: 128977.1719 - val_loss: 31562665984.0000 - val_mae: 125279.8594
Epoch 36/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37012230144.0000 - mae: 126367.0938 - val_loss: 30611314688.0000 - val_mae: 122289.5781
Epoch 37/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 36103618560.0000 - mae: 123454.0156 - val_loss: 29696245760.0000 - val_mae: 119374.4609
Epoch 38/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35219873792.0000 - mae: 120110.0781 - val_loss: 28855369728.0000 - val_mae: 116820.2344
Epoch 39/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 34381533184.0000 - mae: 117795.1719 - val_loss: 28016404480.0000 - val_mae: 113892.1719
Epoch 40/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 33590540288.0000 - mae: 114572.1094 - val_loss: 27235041280.0000 - val_mae: 111191.7812
Epoch 41/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 32812361728.0000 - mae: 111916.9453 - val_loss: 26481821696.0000 - val_mae: 108347.2812
Epoch 42/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 32107108352.0000 - mae: 109129.7031 - val_loss: 25806702592.0000 - val_mae: 105879.1094
Epoch 43/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31442960384.0000 - mae: 106677.1484 - val_loss: 25162833920.0000 - val_mae: 103380.0859
Epoch 44/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30827909120.0000 - mae: 104053.1094 - val_loss: 24575604736.0000 - val_mae: 101016.4297
Epoch 45/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 30259517440.0000 - mae: 101438.6172 - val_loss: 24035444736.0000 - val_mae: 98824.8359
Epoch 46/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 29743687680.0000 - mae: 99251.2188 - val_loss: 23541276672.0000 - val_mae: 96763.6797
Epoch 47/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 29275953152.0000 - mae: 97444.0391 - val_loss: 23087177728.0000 - val_mae: 94787.6016
Epoch 48/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28840804352.0000 - mae: 95491.4375 - val_loss: 22664419328.0000 - val_mae: 92747.9688
Epoch 49/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28436629504.0000 - mae: 93413.5781 - val_loss: 22292733952.0000 - val_mae: 91058.7891
Epoch 50/50
293/293 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28094326784.0000 - mae: 91965.7344 - val_loss: 21982713856.0000 - val_mae: 89869.0547

In [10]:
# Predict on test data
y_pred = model.predict(X_test)

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [14]:
# Evaluate the model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R2 Score:", r2)

Mean Absolute Error (MAE): 93566.984375
Mean Squared Error (MSE): 30514415616.0
Root Mean Squared Error (RMSE): 174683.75887872346
R2 Score: 0.7938160300254822

In [15]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred.flatten()
})

comparison.head(10)

   Actual Price  Predicted Price
0        546800     5.500866e+05
1        550000     5.162752e+05
2        399950     3.886319e+05
3        940000     9.078614e+05
4        545000     7.589786e+05
5        318000     4.067159e+05
6        315000     3.908996e+05
7       1800000     1.672506e+06
8       1250000     1.214328e+06
9        825000     1.013794e+06